GET http://localhost:3000

###
# @name createEvent
POST http://localhost:3000/events
content-type: application/json

{
  "name": "Evento teste",
  "description": "Evento de teste para ser removido depois",
  "date": "2023-02-27T00:00:00",
  "price": 100
}

###
@eventId = {{ createEvent.response.body.id }}

###
GET http://localhost:3000/events

###
GET http://localhost:3000/events/{{ eventId }}

###
PATCH http://localhost:3000/events/{{ eventId }}
content-type: application/json

{
  "name": "Evento atualizado"
}

###
DELETE http://localhost:3000/events/{{ eventId }}
