GET http://localhost:3000

###
# @name createEvent
POST http://localhost:3000/events
content-type: application/json

{
  "name": "Evento Novo",
  "description": "Evento de teste para ser removido depois",
  "date": "2023-02-27T00:00:00",
  "price": 100
}

###
@eventId = {{ createEvent.response.body.id }}

###
GET http://localhost:3000/events

###
GET http://localhost:3000/events/{{ eventId }}

###
PATCH http://localhost:3000/events/{{ eventId }}
content-type: application/json

{
  "name": "Evento novo 2: O Retorno",
  "description": "Evento de teste para ser removido depois",
  "date": "2023-02-27T00:00:00",
  "price": 100
}

###
DELETE http://localhost:3000/events/{{ eventId }}

###################################

# @name createSpot
POST http://localhost:3000/events/{{ eventId }}/spots
content-type: application/json

{
  "name": "A3"
}

###
@spotId = {{ createSpot.response.body.id }}

###
GET http://localhost:3000/events/{{ eventId }}/spots

###
GET http://localhost:3000/events/{{ eventId }}/spots/{{ spotId }}

###
PATCH http://localhost:3000/events/{{ eventId }}/spots/{{ spotId }}
content-type: application/json

{
  "name": "A2"
}

###
DELETE http://localhost:3000/events/{{ eventId }}/spots/{{ spotId }}

###
@spotName = {{ createSpot.response.body.name }}

###
POST http://localhost:3000/events/{{ eventId }}/reserve
content-type: application/json
x-api-token: Nest123

{
  "spots": ["{{ spotName }}"],
  "ticket_kind": "full",
  "email": "test@test.com"
}
