GET http://localhost:3001

###
# @name createEvent
POST http://localhost:3001/eventos
content-type: application/json

{
  "nome": "Evento Novo",
  "descricao": "Evento de teste para ser removido depois",
  "data": "2023-02-27T00:00:00",
  "preco": 100
}

###
@eventId = {{ createEvent.response.body.id }}

###
GET http://localhost:3001/eventos

###
GET http://localhost:3001/eventos/{{ eventId }}

###
PATCH http://localhost:3001/eventos/{{ eventId }}
content-type: application/json

{
  "nome": "Evento novo 2: O Retorno",
  "descricao": "Evento de teste para ser removido depois",
  "data": "2023-02-27T00:00:00",
  "preco": 100
}

###
DELETE http://localhost:3001/eventos/{{ eventId }}

###################################

# @name createSpot
POST http://localhost:3001/eventos/{{ eventId }}/lugares
content-type: application/json

{
  "nome": "A1"
}

###
@spotId = {{ createSpot.response.body.id }}

###
GET http://localhost:3001/eventos/{{ eventId }}/lugares

###
GET http://localhost:3001/eventos/{{ eventId }}/lugares/{{ spotId }}

###
PATCH http://localhost:3001/eventos/{{ eventId }}/lugares/{{ spotId }}
content-type: application/json

{
  "nome": "A6"
}

###
DELETE http://localhost:3001/eventos/{{ eventId }}/lugares/{{ spotId }}

###
@spotName = {{ createSpot.response.body.name }}

###
POST http://localhost:3001/eventos/{{ eventId }}/reserve
content-type: application/json
x-api-token: Nest1234

{
  "lugares": ["{{ spotName }}"],
  "tipo_ingresso": "full",
  "email": "test@test.com"
}
